// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkfkqnfcearxlhbkfozt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZmtxbmZjZWFyeGxoYmtmb3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzUxNjgsImV4cCI6MjA2MTExMTE2OH0.88ANiDLqhmNEKpEyVWPMFd8siy4HvE8_O7dHdOgx_sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);